# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83d36d1ccbab06d23ff250ceba55617c78206b6756eaf3754f528018c7229510b8878fd3967379a1db77c07cd4d64a20b706163ba8db2a56b963a339d0e0a3a9

test:
  secret_key_base: 0313e1903f1bc08d0e678941ab06a343f52375044cfee927ede0d0a62c0c62b7c988a1b4df26d45be7bf837cdeb0f7dde54528edaed52185e45afe85af355f33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
